[package]
name = "riscv_sim"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
bytesize = "1.3.0"
clap = { version = "4.5.8", features = ["derive"] }
clap-num = "1.1.1"
colored = "2.1.0"
